# Generated by Django 4.2.7 on 2023-12-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email_id', models.EmailField(max_length=254)),
                ('mobile_no', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
